#!/usr/bin/env bash
# One-time (re-runnable) local identity setup. Generates local.nix --
# gitignored, never committed -- with this machine's OS username and git
# identity. flake.nix requires this file to exist; this repo carries no
# default identity of its own. Run this before bootstrap.sh/rebuild.sh.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
LOCAL_NIX="$DIR/local.nix"

# Wire up this repo's tracked hooks (currently just a pre-commit guard
# against hardcoded /home/<user> paths leaking into tracked files -- see
# CLAUDE.md). Unconditional and idempotent, runs even if the local.nix
# prompt below is declined.
git -C "$DIR" config --local core.hooksPath .githooks

if [ -f "$LOCAL_NIX" ]; then
  read -r -p "$LOCAL_NIX already exists. Overwrite? [y/N] " REPLY
  if [ "$REPLY" != "y" ] && [ "$REPLY" != "Y" ]; then
    echo "Left unchanged."
    exit 0
  fi
fi

OS_USER="$(whoami)"

# Detect a candidate git user.name: already-configured global git identity,
# then the authenticated gh CLI user (skipped gracefully if gh isn't
# installed/authenticated -- gh is Nix-managed by this same repo, so it
# won't be on PATH yet on a brand-new machine's very first run), then the
# owner segment of the origin remote (works once forked+cloned; gives a
# handle, not a real name, consistent with this repo's identity philosophy
# -- see CLAUDE.md).
detect_name() {
  local candidate
  candidate="$(git config --global user.name 2>/dev/null || true)"
  if [ -n "$candidate" ]; then echo "$candidate"; return; fi

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    candidate="$(gh api user --jq .login 2>/dev/null || true)"
    if [ -n "$candidate" ]; then echo "$candidate"; return; fi
  fi

  candidate="$(git -C "$DIR" remote get-url origin 2>/dev/null \
    | sed -E 's#.*[:/]([^/:]+)/[^/]+?(\.git)?$#\1#' || true)"
  if [ -n "$candidate" ]; then echo "$candidate"; return; fi
}

# Detect a candidate git user.email: already-configured global git identity,
# then GitHub's own privacy-preserving noreply address, built from the
# authenticated gh CLI user.
detect_email() {
  local candidate
  candidate="$(git config --global user.email 2>/dev/null || true)"
  if [ -n "$candidate" ]; then echo "$candidate"; return; fi

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    local login id
    login="$(gh api user --jq .login 2>/dev/null || true)"
    id="$(gh api user --jq .id 2>/dev/null || true)"
    if [ -n "$login" ] && [ -n "$id" ]; then
      echo "${id}+${login}@users.noreply.github.com"
      return
    fi
  fi
}

# Auto-detected values are shown, never applied blind -- this repo has
# already been bitten once by identity auto-detection doing the wrong thing
# silently (the GECOS/real-name leak in CLAUDE.md's ~/.gitconfig gotcha).
DETECTED_NAME="$(detect_name || true)"
GIT_NAME=""
while [ -z "$GIT_NAME" ]; do
  read -r -p "Git user.name${DETECTED_NAME:+ [$DETECTED_NAME]}: " GIT_NAME
  GIT_NAME="${GIT_NAME:-$DETECTED_NAME}"
done

DETECTED_EMAIL="$(detect_email || true)"
GIT_EMAIL=""
while [ -z "$GIT_EMAIL" ]; do
  read -r -p "Git user.email${DETECTED_EMAIL:+ [$DETECTED_EMAIL]}: " GIT_EMAIL
  GIT_EMAIL="${GIT_EMAIL:-$DETECTED_EMAIL}"
done

# Escape for embedding as Nix string literals: backslash first, then quote.
nix_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

cat > "$LOCAL_NIX" <<EOF
# Generated by ./init.sh. Gitignored -- never committed. Re-run ./init.sh to change.
{
  user = "$(nix_escape "$OS_USER")";
  gitUserName = "$(nix_escape "$GIT_NAME")";
  gitUserEmail = "$(nix_escape "$GIT_EMAIL")";
}
EOF

echo "Wrote $LOCAL_NIX"
